Models/ErrorViewModel.cs
using System;

namespace PRUEBAPRACTICA.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ReporteDTO.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PRUEBAPRACTICA.Models
{
    public class ReporteDTO
    {
        public string Nombre { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Fecha { get; set; }
        [DataType(DataType.Currency)]
        public decimal Precio { get; set; }
        [DataType(DataType.Currency)]
        public decimal PrecioVenta { get; set; }    
        public string caracteristicas { get; set; }
    }
}

Models/cars.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PRUEBAPRACTICA.Models
{
    public class cars
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public decimal Price { get; set; }
        public List<purchases> purchases { get; set; }
    }
}

Models/customers.cs
using System.Collections.Generic;

namespace PRUEBAPRACTICA.Models
{
    public class customers
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }   
        public string address { get; set; } 
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public List<purchases> purchases { get; set; }

    }
}

Models/purchases.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace PRUEBAPRACTICA.Models
{
    public class purchases
    {
        public int Id { get; set; }
        public int CardId {get;set;}
        public int CustomerId { get; set; }
        public DateTime Date { get; set; }
        public decimal Price { get; set; }

        [ForeignKey("CarId")]
        public virtual customers customer { get; set; }
        [ForeignKey("CustomerId")]
        public virtual cars cars { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PRUEBAPRACTICA.Data;
using PRUEBAPRACTICA.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PRUEBAPRACTICA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private PruebaContext _context;

        public HomeController(ILogger<HomeController> logger, PruebaContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {

            var resultado = _context.puschases.Include(x => x.customer)
                                .Include(x => x.cars).ToList()
                                .Select(x => new ReporteDTO
                                {
                                    Nombre = $"{x.customer.firstname} {x.customer.lastName}",
                                    Fecha = x.Date,
                                    PrecioVenta = x.Price,
                                    Precio = x.cars.Price,
                                    caracteristicas = $"color: {x.cars.Color} año: { x.cars.Year }, modelo: {x.cars.Make}- {x.cars.Year}"
                                });

            return View(resultado);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PruebaLogicaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PRUEBAPRACTICA.Controllers
{
    public class PruebaLogicaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<ReporteDTO>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Reporte Ventas de Autos</h1>
    <br />
    <table class="table" id="reporte"">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioVenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.caracteristicas)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecioVenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.caracteristicas)
                </td>
            </tr>
        }
        </tbody>
    </table>

</div>

Views/PruebaLogica/Index.cshtml
 <div class="container">
     <h1>
         Conclusion de problemas
     </h1>
     <div class="box">
         Basado en el problema: planteado

        Primero dejaria que se fuera la presona que tarda 10 minutos acompañana de la de que tarda 5 minutos, pasado los 5 minutos  
         comenzaria la persona que tarda 2 minutos, para este punto la persona que tarda 10 minutos a avanzado 6 minutos, en este punto 
         comenzaria la que tarda 1 minuto. Esto da lugar a que en todo momento la persona que avanzo lento sea capaz de alumbran a cada uno de los 
         acompañantes sin que se haya acabado la pila del foco.
     </div>

     <div class="customecontenedor">
         Task 10 start --------------------------------------------------------> finish<br />
         Task 5  start  --------------> Task 2 start --------> taskt 1 strart ---> finish
     </div>
     <div class="box">
         En este punto las personas han logrado avanzar en 10 minutos lineales considerando que en ningun momento pararon.
         Ahora bien en el caso de uso en el que la que tuvo los diez minutos haya tomado tiempo repartido para alumbrar a 
         cada uno se deberia considerar la siguiente condicion:

         10 / 5 / 2 --> 1       minuto para alumbrar  el avance del que tarda 5 minutos
         5 / 2 / 2 -->  1.25    minuto para alumbrar  el avance del que tarda 2 minutos
         3 / 1 / 2 -->  1.5     minutos para alumbrar el avance del que tarda 1 minutos

     </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRUEBAPRACTICA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custome.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRUEBAPRACTICA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Reporte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PruebaLogica" asp-action="Index">Prueba Logica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PRUEBAPRACTICA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>